projectApp/projectApp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('testapp/', include('testapp.urls')),
    path('admin/', admin.site.urls),
    path('', include('testapp.urls')),
]

projectApp/testapp/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
from django.urls import path
from django.contrib import admin
from .views import HomePageView

app_name = 'testapp'
# path,function names,rename
urlpatterns = [
    # path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),

    path('', HomePageView.as_view(), name='home'),
]

projectApp/testapp/models.py
# Create your models here.
from django.db import models


class Posts(models.Model):
    text = models.TextField()

    def __str__(self):
        return self.text


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

projectApp/testapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.generic import ListView

from .models import Choice, Question, Posts


def HomePageView(ListView):
    model = Posts
    template_name = 'home.html'
    context_object_name = 'all_posts_list'


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {
        'latest_question_list': latest_question_list,
    }
    return render(request, 'testapp/index.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'testapp/detail.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'testapp/results.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'testapp/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('testapp:results', args=(question.id,)))

projectApp/templates/home.html
<!-- templates/home.html -->
<h1>Message board homepage</h1>
<ul>{% for post in object_list %}
    <li>{{ posts }}</li>
    {% endfor %}
</ul>

projectApp/templates/testapp/detail.html
<form action="{% url 'testapp:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>

projectApp/templates/testapp/index.html
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li><a href="/testapp/{{ question.id }}/">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

projectApp/templates/testapp/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'testapp:detail' question.id %}">Vote again?</a>